Inverted key/value for select options
kadirahq/storybook-addon-knobs pull request #87
Opened 2017-02-21 10:27 UTC by ndbroadbent

In response to #71

2017-02-28 10:58 UTC, mastilver commented
Why not fixing the issue rather that inverting the docs? It's obviously a bug

Also it doesn't fix the issue for `Array`s:

```
select('test', [
  'item1',
  'item2',
  'item3'
], 'item1');
```

When the expected is:

```
select('test', [
  'item1',
  'item2',
  'item3'
], 0);
```

2017-04-08 14:29 UTC, mthuret requested changes

2017-04-08 14:29 UTC, mthuret commented on example/stories/index.js
> +  const favoriteNumber = select('Favorite Number', { 'Seven': 7, 'Forty-two': 42, 'Nine thousand': 9000 }, 42);
I think it would be better to add a new line, keeping the simple "number" example.

2017-04-08 14:32 UTC, mthuret commented
@mastilver Can you explain what you've expected? It seems that this doesn't just invert the doc. 

I think this syntax is more natural. But this is a breaking change. I think it's ok to go for a major version but WDYT @mnmtanish and @apexskier?

2017-04-08 19:29 UTC, mastilver commented
To me the docs sounds right, That's the way I would want it to work. Especially when you take array in consideration

Cc @lifehacket

2017-04-10 15:17 UTC, apexskier commented
I actually very much like this. When I first used knobs, the original syntax was pretty surprising, but this definitely requires a major version bump.

2017-04-15 13:02 UTC, ndelangen commented
Hey @ndbroadbent 

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.
We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

That'd be awesome, thanks!

2017-04-15 13:02 UTC, closed without merging